"use client";

import { MenuView } from "../m/[qrToken]/menu-view";
import type { MenuPayload } from "@/lib/api";

// Local goseller — public/images/menu/ klasorunde olmali.
// Eksik dosya icin Image hata verirse, ProductCard otomatik emoji gradient'e duser.
// GitHub Pages gibi basePath altinda servis edilen ortamlarda src'lerin manuel prefix'lenmesi gerekiyor.
const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const img = (name: string): string => `${BASE_PATH}/images/menu/${name}`;

const DEMO_DATA: MenuPayload = {
  table: { id: "demo-table", label: "İ-1", section: "İç Salon" },
  restaurant: {
    id: "demo-restaurant",
    tenantId: "demo-tenant",
    name: "Lezzet Köşesi",
    logoUrl: `${BASE_PATH}/images/logo.png`,
    coverUrl: `${BASE_PATH}/images/cover.jpg`,
    currency: "TRY",
    defaultLang: "TR",
    socialLinks: {},
    openingHours: {},
  },
  categories: [
    {
      id: "cat-1",
      name: { TR: "Çorbalar", EN: "Soups" },
      description: null,
      imageUrl: null,
      sortOrder: 1,
      products: [
        {
          id: "p1",
          name: { TR: "Mercimek Çorbası", EN: "Lentil Soup" },
          description: { TR: "Geleneksel kırmızı mercimek çorbası, ev yapımı tereyağı ve naneli", EN: "Traditional red lentil soup with homemade butter and mint" },
          ingredients: { TR: "Kırmızı mercimek, soğan, havuç, tereyağı, baharatlar", EN: "Red lentil, onion, carrot, butter, spices" },
          basePrice: "65",
          prepTimeMin: 5,
          emoji: "🍲",
          tags: ["VEGAN"],
          allergens: [],
          isAvailable: true,
          images: [{ url: img("mercimek-corbasi.jpg"), isPrimary: true }],
          variants: [],
        },
        {
          id: "p2",
          name: { TR: "Ezogelin Çorbası", EN: "Ezogelin Soup" },
          description: { TR: "Bulgur ve mercimekli yöresel çorba, kırmızı biber yağı ile", EN: "Lentil and bulgur regional soup, drizzled with chili oil" },
          ingredients: null,
          basePrice: "75",
          prepTimeMin: 6,
          emoji: "🥣",
          tags: [],
          allergens: ["GLUTEN"],
          isAvailable: true,
          images: [{ url: img("ezogelin-corbasi.jpg"), isPrimary: true }],
          variants: [],
        },
        {
          id: "p3",
          name: { TR: "Domates Çorbası", EN: "Tomato Soup" },
          description: { TR: "Közlenmiş domatesle hazırlanmış, kaşar peyniri rendesi ve kruton ile", EN: "Made with roasted tomatoes, served with grated cheese and croutons" },
          ingredients: { TR: "Domates, soğan, sarımsak, tereyağı, kaşar", EN: "Tomato, onion, garlic, butter, cheddar" },
          basePrice: "70",
          prepTimeMin: 6,
          emoji: "🍅",
          tags: [],
          allergens: ["LACTOSE", "GLUTEN"],
          isAvailable: true,
          images: [{ url: img("domates-corbasi.jpg"), isPrimary: true }],
          variants: [],
        },
        {
          id: "p4",
          name: { TR: "Yayla Çorbası", EN: "Yayla Soup" },
          description: { TR: "Yoğurtlu pirinç çorbası, naneli tereyağı sosu ile", EN: "Yogurt and rice soup, finished with mint butter" },
          ingredients: null,
          basePrice: "70",
          prepTimeMin: 7,
          emoji: "🥛",
          tags: ["CHEF_PICK"],
          allergens: ["LACTOSE"],
          isAvailable: true,
          images: [{ url: img("yayla-corbasi.jpg"), isPrimary: true }],
          variants: [],
        },
      ],
    },
    {
      id: "cat-2",
      name: { TR: "Ana Yemekler", EN: "Main Dishes" },
      description: null,
      imageUrl: null,
      sortOrder: 2,
      products: [
        {
          id: "p5",
          name: { TR: "Adana Kebap", EN: "Adana Kebab" },
          description: { TR: "Acılı zırh kıyma, közlenmiş biber ve bulgur pilavı eşliğinde", EN: "Spicy minced lamb on charcoal, with grilled pepper and bulgur pilaf" },
          ingredients: { TR: "Kuzu kıyma, biber, baharatlar, közlenmiş sebzeler", EN: "Lamb mince, pepper, spices, grilled vegetables" },
          basePrice: "320",
          prepTimeMin: 20,
          emoji: "🍢",
          tags: ["SPICY", "CHEF_PICK"],
          allergens: [],
          isAvailable: true,
          images: [{ url: img("adana-kebap.jpg"), isPrimary: true }],
          variants: [
            { id: "v1", name: { TR: "Tek Porsiyon", EN: "Single" }, priceDelta: "0", isDefault: true },
            { id: "v2", name: { TR: "Çift Porsiyon", EN: "Double" }, priceDelta: "180", isDefault: false },
          ],
        },
        {
          id: "p6",
          name: { TR: "Urfa Kebap", EN: "Urfa Kebab" },
          description: { TR: "Acısız zırh kıyma, soğan ve sumakla", EN: "Mild minced lamb skewer, with onion and sumac" },
          ingredients: { TR: "Kuzu kıyma, soğan, sumak, baharatlar", EN: "Lamb mince, onion, sumac, spices" },
          basePrice: "320",
          prepTimeMin: 20,
          emoji: "🍢",
          tags: [],
          allergens: [],
          isAvailable: true,
          images: [{ url: img("urfa-kebap.jpg"), isPrimary: true }],
          variants: [
            { id: "v6", name: { TR: "Tek Porsiyon", EN: "Single" }, priceDelta: "0", isDefault: true },
            { id: "v7", name: { TR: "Çift Porsiyon", EN: "Double" }, priceDelta: "180", isDefault: false },
          ],
        },
        {
          id: "p7",
          name: { TR: "Tavuk Şiş", EN: "Chicken Skewer" },
          description: { TR: "Marine edilmiş tavuk göğsü, közlenmiş sebzelerle", EN: "Marinated chicken breast with grilled vegetables" },
          ingredients: null,
          basePrice: "260",
          prepTimeMin: 18,
          emoji: "🍗",
          tags: [],
          allergens: [],
          isAvailable: true,
          images: [{ url: img("tavuk-sis.jpg"), isPrimary: true }],
          variants: [],
        },
        {
          id: "p8",
          name: { TR: "Izgara Köfte", EN: "Grilled Meatballs" },
          description: { TR: "El yapımı köfte, pirinç pilavı ve közlenmiş biber ile", EN: "Hand-made meatballs with rice pilaf and grilled pepper" },
          ingredients: null,
          basePrice: "280",
          prepTimeMin: 15,
          emoji: "🍖",
          tags: [],
          allergens: ["GLUTEN"],
          isAvailable: true,
          images: [{ url: img("izgara-kofte.jpg"), isPrimary: true }],
          variants: [],
        },
        {
          id: "p9",
          name: { TR: "İskender", EN: "Iskender Kebab" },
          description: { TR: "İnce dilim döner, domates sosu, yoğurt ve eritilmiş tereyağı ile", EN: "Thin sliced doner with tomato sauce, yogurt and melted butter" },
          ingredients: { TR: "Dana eti, pide, yoğurt, domates sosu, tereyağı", EN: "Beef, pita, yogurt, tomato sauce, butter" },
          basePrice: "350",
          prepTimeMin: 15,
          emoji: "🥩",
          tags: ["CHEF_PICK"],
          allergens: ["GLUTEN", "LACTOSE"],
          isAvailable: true,
          images: [{ url: img("iskender.jpg"), isPrimary: true }],
          variants: [],
        },
        {
          id: "p10",
          name: { TR: "Lahmacun", EN: "Lahmacun" },
          description: { TR: "İnce hamur üzerinde acılı kıymalı harç, limon ve maydanozla", EN: "Thin dough topped with spiced minced meat, served with lemon and parsley" },
          ingredients: null,
          basePrice: "85",
          prepTimeMin: 8,
          emoji: "🫓",
          tags: ["SPICY"],
          allergens: ["GLUTEN"],
          isAvailable: true,
          images: [{ url: img("lahmacun.jpg"), isPrimary: true }],
          variants: [],
        },
        {
          id: "p11",
          name: { TR: "Karışık Pide", EN: "Mixed Pide" },
          description: { TR: "Kaşarlı, sucuklu ve kıymalı klasik pide", EN: "Classic pide with cheese, sucuk and minced meat" },
          ingredients: null,
          basePrice: "180",
          prepTimeMin: 12,
          emoji: "🥖",
          tags: [],
          allergens: ["GLUTEN", "LACTOSE"],
          isAvailable: true,
          images: [{ url: img("pide.jpg"), isPrimary: true }],
          variants: [],
        },
      ],
    },
    {
      id: "cat-3",
      name: { TR: "Tatlılar", EN: "Desserts" },
      description: null,
      imageUrl: null,
      sortOrder: 3,
      products: [
        {
          id: "p12",
          name: { TR: "Künefe", EN: "Kunefe" },
          description: { TR: "Antep fıstığı, kaymak ile servis edilir, sıcak", EN: "With pistachio and clotted cream, served hot" },
          ingredients: null,
          basePrice: "180",
          prepTimeMin: 10,
          emoji: "🧆",
          tags: ["CHEF_PICK"],
          allergens: ["LACTOSE", "NUT"],
          isAvailable: true,
          images: [{ url: img("kunefe.jpg"), isPrimary: true }],
          variants: [],
        },
        {
          id: "p13",
          name: { TR: "Sütlaç", EN: "Rice Pudding" },
          description: { TR: "Fırınlanmış geleneksel sütlaç, üzeri tarçınlı", EN: "Baked traditional rice pudding with cinnamon" },
          ingredients: null,
          basePrice: "120",
          prepTimeMin: 3,
          emoji: "🍮",
          tags: [],
          allergens: ["LACTOSE"],
          isAvailable: true,
          images: [{ url: img("sutlac.jpg"), isPrimary: true }],
          variants: [],
        },
        {
          id: "p14",
          name: { TR: "Baklava", EN: "Baklava" },
          description: { TR: "Antep fıstıklı, ince yufkalı, şerbetli geleneksel tatlı", EN: "Pistachio baklava with thin filo and syrup" },
          ingredients: { TR: "Yufka, Antep fıstığı, tereyağı, şerbet", EN: "Filo, pistachio, butter, syrup" },
          basePrice: "200",
          prepTimeMin: 3,
          emoji: "🍯",
          tags: ["CHEF_PICK"],
          allergens: ["GLUTEN", "LACTOSE", "NUT"],
          isAvailable: true,
          images: [{ url: img("baklava.jpg"), isPrimary: true }],
          variants: [],
        },
        {
          id: "p15",
          name: { TR: "Kazandibi", EN: "Kazandibi" },
          description: { TR: "Tabanı karamelize edilmiş geleneksel sütlü tatlı", EN: "Traditional milk dessert with caramelized base" },
          ingredients: null,
          basePrice: "130",
          prepTimeMin: 3,
          emoji: "🍯",
          tags: [],
          allergens: ["LACTOSE", "GLUTEN"],
          isAvailable: true,
          images: [{ url: img("kazandibi.jpg"), isPrimary: true }],
          variants: [],
        },
      ],
    },
    {
      id: "cat-4",
      name: { TR: "İçecekler", EN: "Beverages" },
      description: null,
      imageUrl: null,
      sortOrder: 4,
      products: [
        {
          id: "p16",
          name: { TR: "Ayran", EN: "Ayran" },
          description: { TR: "Ev yapımı, tuzlu, soğuk", EN: "Homemade, salted, ice-cold" },
          ingredients: null,
          basePrice: "35",
          prepTimeMin: 1,
          emoji: "🥛",
          tags: [],
          allergens: ["LACTOSE"],
          isAvailable: true,
          images: [{ url: img("ayran.jpg"), isPrimary: true }],
          variants: [],
        },
        {
          id: "p17",
          name: { TR: "Türk Kahvesi", EN: "Turkish Coffee" },
          description: { TR: "Bakır cezvede pişirilmiş, lokum eşliğinde", EN: "Brewed in copper pot, served with Turkish delight" },
          ingredients: null,
          basePrice: "80",
          prepTimeMin: 5,
          emoji: "☕",
          tags: ["CHEF_PICK"],
          allergens: [],
          isAvailable: true,
          images: [{ url: img("turk-kahvesi.jpg"), isPrimary: true }],
          variants: [
            { id: "v3", name: { TR: "Sade", EN: "Plain" }, priceDelta: "0", isDefault: true },
            { id: "v4", name: { TR: "Orta", EN: "Medium" }, priceDelta: "0", isDefault: false },
            { id: "v5", name: { TR: "Şekerli", EN: "Sweet" }, priceDelta: "0", isDefault: false },
          ],
        },
        {
          id: "p18",
          name: { TR: "Çay", EN: "Turkish Tea" },
          description: { TR: "Demli, ince belli bardakta", EN: "Brewed, served in tulip glass" },
          ingredients: null,
          basePrice: "20",
          prepTimeMin: 2,
          emoji: "🍵",
          tags: [],
          allergens: [],
          isAvailable: true,
          images: [{ url: img("cay.jpg"), isPrimary: true }],
          variants: [],
        },
        {
          id: "p19",
          name: { TR: "Kola", EN: "Cola" },
          description: { TR: "Soğuk kola, 330ml", EN: "Cold cola, 330ml" },
          ingredients: null,
          basePrice: "40",
          prepTimeMin: 1,
          emoji: "🥤",
          tags: [],
          allergens: [],
          isAvailable: true,
          images: [{ url: img("kola.jpg"), isPrimary: true }],
          variants: [],
        },
        {
          id: "p20",
          name: { TR: "Limonata", EN: "Lemonade" },
          description: { TR: "Taze sıkılmış limon, naneli", EN: "Freshly squeezed lemon with mint" },
          ingredients: null,
          basePrice: "55",
          prepTimeMin: 3,
          emoji: "🍋",
          tags: ["NEW"],
          allergens: [],
          isAvailable: true,
          images: [{ url: img("limonata.jpg"), isPrimary: true }],
          variants: [],
        },
      ],
    },
  ],
};

export default function DemoPage(): React.ReactElement {
  return <MenuView qrToken="demo" initial={DEMO_DATA} />;
}
